/**
 * S1 — Mouline : données initiales du catalogue d'aides
 * 10 aides représentatives pour le MVP (régions pilotes : AuRA + Aube)
 *
 * NB : ces données sont la source de vérité TypeScript.
 * La migration SQL 002_seed_aides.sql en est la copie pour le déploiement.
 */

import type { AideInput } from '@/lib/validations/aide'

export const SEED_AIDES: AideInput[] = [
  // ── État / DRAC ─────────────────────────────────────────────────────────────

  {
    nom: 'Subvention DRAC — Restauration MH classés',
    organisme: 'DRAC (Ministère de la Culture)',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'prive', 'association'],
    type_monument_eligible: ['classe'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.5,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      cumulable_avec: ['fondation_du_patrimoine_label', 'region_aura_patrimoine'],
      notes: 'Taux majoré possible pour les monuments en péril.',
    },
    url_source: 'https://www.culturecommunication.gouv.fr/Thematiques/Patrimoine/Monuments-historiques/Aides-a-la-restauration-des-monuments-historiques',
    external_id: null,
    is_active: true,
  },

  {
    nom: 'Subvention DRAC — Restauration MH inscrits',
    organisme: 'DRAC (Ministère de la Culture)',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'prive', 'association'],
    type_monument_eligible: ['inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.4,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      cumulable_avec: ['fondation_du_patrimoine_label'],
    },
    url_source: 'https://www.culturecommunication.gouv.fr/Thematiques/Patrimoine/Monuments-historiques/Aides-a-la-restauration-des-monuments-historiques',
    external_id: null,
    is_active: true,
  },

  {
    nom: 'FSIL — Fonds de Soutien à l\'Investissement Local (volet patrimoine)',
    organisme: 'Préfecture / DRAC',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'conservation',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.8,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Réservé aux collectivités locales.',
    },
    url_source: 'https://www.prefectures-regions.gouv.fr/auvergne-rhone-alpes/Section-actualites/Fonds-de-soutien-a-l-investissement-local',
    external_id: null,
    is_active: true,
  },

  // ── Région Auvergne-Rhône-Alpes ─────────────────────────────────────────────

  {
    nom: 'Aide régionale au patrimoine — AuRA',
    organisme: 'Région Auvergne-Rhône-Alpes',
    type_aide: 'subvention',
    source: 'region',
    categorie: 'restauration',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 150000,
    taux_max: 0.4,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      cumulable_avec: ['drac_restauration_mh_classes'],
    },
    url_source: 'https://www.auvergnerhonealpes.fr/aide/patrimoine-historique',
    external_id: null,
    is_active: true,
  },

  {
    nom: 'Aide au patrimoine rural non protégé — AuRA',
    organisme: 'Région Auvergne-Rhône-Alpes',
    type_aide: 'subvention',
    source: 'region',
    categorie: 'conservation',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['spr', 'label_fdp', 'non_protege'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 50000,
    taux_max: 0.3,
    plafond_financement_public: 0.8,
    regles_cumul: null,
    url_source: 'https://www.auvergnerhonealpes.fr/aide/patrimoine-rural',
    external_id: null,
    is_active: true,
  },

  // ── Fondation du Patrimoine ──────────────────────────────────────────────────

  {
    nom: 'Fondation du Patrimoine — Label (souscription publique)',
    organisme: 'Fondation du Patrimoine',
    type_aide: 'appel_projet',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['prive', 'association'],
    type_monument_eligible: ['label_fdp', 'non_protege'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Le label ouvre à la déduction fiscale pour les donateurs.',
    },
    url_source: 'https://www.fondation-patrimoine.org/les-aides/le-label',
    external_id: null,
    is_active: true,
  },

  {
    nom: 'Fondation du Patrimoine — Mission Patrimoine (Loto du Patrimoine)',
    organisme: 'Fondation du Patrimoine / Mission Stéphane Bern',
    type_aide: 'subvention',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'prive', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Sélection nationale annuelle sur dossier.',
    },
    url_source: 'https://www.fondation-patrimoine.org/les-aides/mission-patrimoine',
    external_id: null,
    is_active: true,
  },

  // ── Fondations privées ──────────────────────────────────────────────────────

  {
    nom: 'VMF — Aide à la restauration du patrimoine privé',
    organisme: 'Vieilles Maisons Françaises (VMF)',
    type_aide: 'subvention',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['prive', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 10000,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: null,
    url_source: 'https://www.vmf.net/aides',
    external_id: null,
    is_active: true,
  },

  {
    nom: 'Sauvegarde de l\'Art Français — Aide à la restauration',
    organisme: 'Sauvegarde de l\'Art Français',
    type_aide: 'subvention',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: ['mobilier', 'vitraux', 'sculpture'],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 15000,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Priorité aux mobiliers et objets d\'art religieux.',
    },
    url_source: 'https://www.sauvegardeartfrancais.fr/aides',
    external_id: null,
    is_active: true,
  },

  // ── Europe ──────────────────────────────────────────────────────────────────

  {
    nom: 'FEDER — Volet patrimoine et développement territorial',
    organisme: 'Union Européenne / Région AuRA',
    type_aide: 'subvention',
    source: 'europe',
    categorie: 'conservation',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 500000,
    taux_max: 0.5,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Obligation de co-financement local minimum 20%.',
    },
    url_source: 'https://www.auvergnerhonealpes.eu/feder',
    external_id: null,
    is_active: true,
  },
]
