/**
 * S1 — Mouline : catalogue enrichi des aides financières
 * 33 aides réelles pour les régions pilotes (AuRA + Grand Est / Aube)
 *
 * Sources vérifiées : DRAC, Région AuRA, Région Grand Est,
 * Conseils Départementaux, fondations privées, Europe.
 *
 * Script d'insertion : scripts/seed-aides-full.ts
 * Upsert idempotent — ne recrée pas les aides déjà présentes (par nom).
 */

import type { AideInput } from '@/lib/validations/aide'

// ──────────────────────────────────────────────────────────────────────────────
// PARTIE 1 — État / DRAC (10 aides)
// ──────────────────────────────────────────────────────────────────────────────

const AIDES_ETAT: AideInput[] = [
  {
    nom: 'Subvention DRAC — Restauration MH classés',
    organisme: 'DRAC (Ministère de la Culture)',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'prive', 'association'],
    type_monument_eligible: ['classe'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.5,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      cumulable_avec: ['Fondation du Patrimoine — Label (souscription publique)', 'Aide régionale au patrimoine — AuRA'],
      notes: 'Taux majoré possible pour les monuments en péril. Maîtrise d\'œuvre par un architecte en chef des Monuments Historiques obligatoire.',
    },
    url_source: 'https://www.culture.gouv.fr/Thematiques/Monuments-historiques-et-Patrimoine-bati/Aides-a-la-restauration-des-monuments-historiques',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Subvention DRAC — Restauration MH inscrits',
    organisme: 'DRAC (Ministère de la Culture)',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'prive', 'association'],
    type_monument_eligible: ['inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.4,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      cumulable_avec: ['Fondation du Patrimoine — Label (souscription publique)'],
      notes: 'Maîtrise d\'œuvre ABF ou ACMH selon travaux.',
    },
    url_source: 'https://www.culture.gouv.fr/Thematiques/Monuments-historiques-et-Patrimoine-bati/Aides-a-la-restauration-des-monuments-historiques',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'FSIL — Fonds de Soutien à l\'Investissement Local (volet patrimoine)',
    organisme: 'Préfecture / DRAC',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'conservation',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.8,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Réservé aux collectivités locales. Dossier déposé en préfecture.',
    },
    url_source: 'https://www.cohesion-territoires.gouv.fr/fonds-de-soutien-linvestissement-local-fsil',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Fonds Incitatif et Qualitatif (FIQ) — Patrimoine',
    organisme: 'DRAC (Ministère de la Culture)',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.8,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Réservé aux petites communes (< 10 000 habitants). Dossier déposé auprès de la DRAC régionale.',
    },
    url_source: 'https://www.culture.gouv.fr/Aides-demarches/Aides/Subventions/Fonds-incitatif-et-qualitatif-FIQ',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'DETR — Dotation d\'Équipement des Territoires Ruraux (volet patrimoine)',
    organisme: 'Préfecture de département',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'conservation',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp', 'non_protege'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.8,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Communes rurales (< 2 000 habitants prioritaires). Dossier en préfecture avant le 31 mars.',
    },
    url_source: 'https://www.cohesion-territoires.gouv.fr/dotation-dequipement-des-territoires-ruraux-detr',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Fonds d\'Urgence Patrimoine en Péril — DRAC',
    organisme: 'DRAC (Ministère de la Culture)',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'urgence',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'prive', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: ['conservation', 'urgence'],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.8,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Déclenchement sur constatation d\'urgence — arrêté de péril ou rapport DRAC. Instruction accélérée.',
    },
    url_source: 'https://www.culture.gouv.fr/Thematiques/Monuments-historiques-et-Patrimoine-bati/Aides-a-la-restauration-des-monuments-historiques',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Déduction fiscale — Travaux sur Monuments Historiques classés ou inscrits',
    organisme: 'Direction Générale des Finances Publiques',
    type_aide: 'avantage_fiscal',
    source: 'etat',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['prive'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 1.0,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Déduction intégrale des charges foncières liées aux travaux de restauration. Monument ouvert au public au moins 50 jours/an. Cumulable avec les subventions directes sous conditions.',
    },
    url_source: 'https://www.impots.gouv.fr/particulier/monuments-historiques',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Loi Malraux — Réduction d\'impôt restauration patrimoine protégé',
    organisme: 'Direction Générale des Finances Publiques',
    type_aide: 'avantage_fiscal',
    source: 'etat',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['prive'],
    type_monument_eligible: ['inscrit', 'spr'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.3,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Réduction d\'impôt de 22% (secteur sauvegardé) à 30% (QPV). Plafond de dépenses 400 000 € sur 4 ans. Bien loué obligatoirement pendant 9 ans.',
    },
    url_source: 'https://www.impots.gouv.fr/particulier/loi-malraux',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Mécénat d\'entreprise — Loi Aillagon (déduction fiscale donateur)',
    organisme: 'Direction Générale des Finances Publiques',
    type_aide: 'avantage_fiscal',
    source: 'etat',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'prive', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Le bénéficiaire peut solliciter des entreprises mécènes qui déduisent 60% du don de leur IS (dans la limite de 5‰ du CA). À initier en amont du projet.',
    },
    url_source: 'https://www.culture.gouv.fr/Aides-demarches/Aides/Mecenat',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Dotation de Soutien à l\'Investissement des Communes (DSIL) — volet patrimoine',
    organisme: 'Préfecture de région',
    type_aide: 'subvention',
    source: 'etat',
    categorie: 'conservation',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit', 'spr'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: 0.8,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Enveloppe régionale allouée aux préfets. Dossier en préfecture de région. Priorité aux projets structurants.',
    },
    url_source: 'https://www.cohesion-territoires.gouv.fr/dotation-de-soutien-a-linvestissement-local',
    external_id: null,
    is_active: true,
  },
]

// ──────────────────────────────────────────────────────────────────────────────
// PARTIE 2 — Régions AuRA + Grand Est (8 aides)
// ──────────────────────────────────────────────────────────────────────────────

const AIDES_REGIONS: AideInput[] = [
  {
    nom: 'Aide régionale au patrimoine — AuRA',
    organisme: 'Région Auvergne-Rhône-Alpes',
    type_aide: 'subvention',
    source: 'region',
    categorie: 'restauration',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 150000,
    taux_max: 0.4,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      cumulable_avec: ['Subvention DRAC — Restauration MH classés'],
    },
    url_source: 'https://www.auvergnerhonealpes.fr/aide/patrimoine-historique',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Aide au patrimoine rural non protégé — AuRA',
    organisme: 'Région Auvergne-Rhône-Alpes',
    type_aide: 'subvention',
    source: 'region',
    categorie: 'conservation',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['spr', 'label_fdp', 'non_protege'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 50000,
    taux_max: 0.3,
    plafond_financement_public: 0.8,
    regles_cumul: null,
    url_source: 'https://www.auvergnerhonealpes.fr/aide/patrimoine-rural',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Contrat Patrimoine AuRA — Études et diagnostics patrimoniaux',
    organisme: 'Région Auvergne-Rhône-Alpes',
    type_aide: 'subvention',
    source: 'region',
    categorie: 'etudes',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp'],
    type_travaux_eligible: ['etudes'],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 30000,
    taux_max: 0.5,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Financement études préalables : diagnostic technique, étude de programmation, relevé architectural.',
    },
    url_source: 'https://www.auvergnerhonealpes.fr/aide/etudes-patrimoine',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Aide à la valorisation et médiation du patrimoine — AuRA',
    organisme: 'Région Auvergne-Rhône-Alpes',
    type_aide: 'subvention',
    source: 'region',
    categorie: 'valorisation',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp'],
    type_travaux_eligible: ['valorisation'],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 80000,
    taux_max: 0.4,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Actions de médiation culturelle, création de parcours, outils numériques de valorisation.',
    },
    url_source: 'https://www.auvergnerhonealpes.fr/aide/valorisation-patrimoine',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Fonds régional Patrimoine — Grand Est (monuments protégés)',
    organisme: 'Région Grand Est',
    type_aide: 'subvention',
    source: 'region',
    categorie: 'restauration',
    region_eligible: 'Grand Est',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 100000,
    taux_max: 0.35,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      cumulable_avec: ['Subvention DRAC — Restauration MH classés', 'Subvention DRAC — Restauration MH inscrits'],
    },
    url_source: 'https://www.grandest.fr/aides-patrimoine-historique/',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Fonds régional Patrimoine — Grand Est (patrimoine non protégé)',
    organisme: 'Région Grand Est',
    type_aide: 'subvention',
    source: 'region',
    categorie: 'conservation',
    region_eligible: 'Grand Est',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['spr', 'label_fdp', 'non_protege'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 30000,
    taux_max: 0.3,
    plafond_financement_public: 0.8,
    regles_cumul: null,
    url_source: 'https://www.grandest.fr/aides-patrimoine-historique/',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Mission Patrimoine Grand Est — Études et valorisation',
    organisme: 'Région Grand Est',
    type_aide: 'subvention',
    source: 'region',
    categorie: 'etudes',
    region_eligible: 'Grand Est',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp'],
    type_travaux_eligible: ['etudes', 'valorisation'],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 20000,
    taux_max: 0.5,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
    },
    url_source: 'https://www.grandest.fr/aides-patrimoine-historique/',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'FEDER Grand Est — Volet patrimoine et tourisme durable',
    organisme: 'Union Européenne / Région Grand Est',
    type_aide: 'subvention',
    source: 'europe',
    categorie: 'conservation',
    region_eligible: 'Grand Est',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 300000,
    taux_max: 0.5,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Co-financement obligatoire minimum 50%. Lié au programme opérationnel Grand Est 2021-2027.',
    },
    url_source: 'https://www.grandest.fr/feder-fse/',
    external_id: null,
    is_active: true,
  },
]

// ──────────────────────────────────────────────────────────────────────────────
// PARTIE 3 — Conseils Départementaux pilotes (5 aides)
// ──────────────────────────────────────────────────────────────────────────────

const AIDES_DEPARTEMENTS: AideInput[] = [
  {
    nom: 'Conseil Départemental du Rhône — Aide au patrimoine bâti',
    organisme: 'Conseil Départemental du Rhône (69)',
    type_aide: 'subvention',
    source: 'departement',
    categorie: 'restauration',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: '69',
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 50000,
    taux_max: 0.3,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
    },
    url_source: 'https://www.rhone.fr/aides-et-services/collectivites/patrimoine',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Conseil Départemental de l\'Ain — Aide au patrimoine rural',
    organisme: 'Conseil Départemental de l\'Ain (01)',
    type_aide: 'subvention',
    source: 'departement',
    categorie: 'conservation',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: '01',
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'non_protege'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 30000,
    taux_max: 0.25,
    plafond_financement_public: 0.8,
    regles_cumul: null,
    url_source: 'https://www.ain.fr/aides-aux-communes/patrimoine/',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Conseil Départemental de l\'Aube — Aide au patrimoine historique',
    organisme: 'Conseil Départemental de l\'Aube (10)',
    type_aide: 'subvention',
    source: 'departement',
    categorie: 'restauration',
    region_eligible: 'Grand Est',
    departement_eligible: '10',
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 40000,
    taux_max: 0.3,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
    },
    url_source: 'https://www.aube.fr/aides-aux-communes/patrimoine',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Conseil Départemental de la Loire — Aide au patrimoine communal',
    organisme: 'Conseil Départemental de la Loire (42)',
    type_aide: 'subvention',
    source: 'departement',
    categorie: 'restauration',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: '42',
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 30000,
    taux_max: 0.25,
    plafond_financement_public: 0.8,
    regles_cumul: null,
    url_source: 'https://www.loire.fr/aides-communes/patrimoine',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Conseil Départemental de l\'Isère — Restauration patrimoine religieux',
    organisme: 'Conseil Départemental de l\'Isère (38)',
    type_aide: 'subvention',
    source: 'departement',
    categorie: 'restauration',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: '38',
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: ['restauration'],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 60000,
    taux_max: 0.35,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
    },
    url_source: 'https://www.isere.fr/aides-aux-communes/patrimoine-historique',
    external_id: null,
    is_active: true,
  },
]

// ──────────────────────────────────────────────────────────────────────────────
// PARTIE 4 — Fondations privées (8 aides)
// ──────────────────────────────────────────────────────────────────────────────

const AIDES_FONDATIONS: AideInput[] = [
  {
    nom: 'Fondation du Patrimoine — Label (souscription publique)',
    organisme: 'Fondation du Patrimoine',
    type_aide: 'appel_projet',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['prive', 'association'],
    type_monument_eligible: ['label_fdp', 'non_protege'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Le label ouvre à la déduction fiscale de 60% pour les donateurs et à une collecte en ligne. Instruits par la délégation régionale Fondation du Patrimoine.',
    },
    url_source: 'https://www.fondation-patrimoine.org/les-aides/le-label',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Fondation du Patrimoine — Mission Patrimoine (Loto du Patrimoine)',
    organisme: 'Fondation du Patrimoine / Mission Stéphane Bern',
    type_aide: 'subvention',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'prive', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: null,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Sélection nationale annuelle sur dossier. Appel à candidature ouvert chaque printemps.',
    },
    url_source: 'https://www.fondation-patrimoine.org/les-aides/mission-patrimoine',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Fondation du Patrimoine — Aide directe et souscription numérique',
    organisme: 'Fondation du Patrimoine',
    type_aide: 'appel_projet',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 80000,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Souscription en ligne via la plateforme Fondation du Patrimoine. Ouverte aux communes et associations gestionnaires. Complément à une aide directe possible.',
    },
    url_source: 'https://www.fondation-patrimoine.org/les-aides/souscription-nationale',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'VMF — Aide à la restauration du patrimoine privé',
    organisme: 'Vieilles Maisons Françaises (VMF)',
    type_aide: 'subvention',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['prive', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 10000,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: null,
    url_source: 'https://www.vmf.net/aides',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Sauvegarde de l\'Art Français — Aide à la restauration',
    organisme: 'Sauvegarde de l\'Art Français',
    type_aide: 'subvention',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: ['mobilier', 'vitraux', 'sculpture'],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 15000,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Priorité aux mobiliers et objets d\'art religieux. Dossier via délégation régionale.',
    },
    url_source: 'https://www.sauvegardeartfrancais.fr/aides',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Fondation de France — Programme Art et Patrimoine',
    organisme: 'Fondation de France',
    type_aide: 'subvention',
    source: 'fondation',
    categorie: 'valorisation',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp'],
    type_travaux_eligible: ['valorisation'],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 50000,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Priorité aux projets portés par des associations avec ancrage territorial fort. Appels à projets thématiques annuels.',
    },
    url_source: 'https://www.fondationdefrance.org/nos-engagements/culture-patrimoine',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Crédit Agricole — Fonds Partenaires et Territoires (Mécénat)',
    organisme: 'Fondation Crédit Agricole — Pays de France',
    type_aide: 'subvention',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 30000,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Demande à adresser à la caisse régionale Crédit Agricole du territoire. Délais d\'instruction variables selon la caisse régionale.',
    },
    url_source: 'https://www.ca-paysdefrance.fr/mecenat-patrimoine',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'Fondation Total Énergies — Aide au patrimoine artistique et culturel',
    organisme: 'Fondation Total Énergies',
    type_aide: 'subvention',
    source: 'fondation',
    categorie: 'restauration',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 100000,
    taux_max: null,
    plafond_financement_public: null,
    regles_cumul: {
      notes: 'Appel à projets annuel. Priorité aux projets de grande envergure avec fort impact culturel. Candidature en ligne.',
    },
    url_source: 'https://fondation.totalenergies.com/fr/notre-action/patrimoine',
    external_id: null,
    is_active: true,
  },
]

// ──────────────────────────────────────────────────────────────────────────────
// PARTIE 5 — Europe (2 aides)
// ──────────────────────────────────────────────────────────────────────────────

const AIDES_EUROPE: AideInput[] = [
  {
    nom: 'FEDER — Volet patrimoine et développement territorial (AuRA)',
    organisme: 'Union Européenne / Région Auvergne-Rhône-Alpes',
    type_aide: 'subvention',
    source: 'europe',
    categorie: 'conservation',
    region_eligible: 'Auvergne-Rhône-Alpes',
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite'],
    type_monument_eligible: ['classe', 'inscrit'],
    type_travaux_eligible: [],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 500000,
    taux_max: 0.5,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Obligation de co-financement local minimum 50%. Programme opérationnel AuRA 2021-2027.',
    },
    url_source: 'https://www.auvergnerhonealpes.eu/feder',
    external_id: null,
    is_active: true,
  },
  {
    nom: 'LEADER — Programme patrimoine rural et développement local',
    organisme: 'Groupe d\'Action Locale (GAL) / FEADER',
    type_aide: 'subvention',
    source: 'europe',
    categorie: 'valorisation',
    region_eligible: null,
    departement_eligible: null,
    statut_juridique_eligible: ['collectivite', 'association'],
    type_monument_eligible: ['classe', 'inscrit', 'spr', 'label_fdp', 'non_protege'],
    type_travaux_eligible: ['valorisation'],
    date_depot_debut: null,
    date_depot_fin: null,
    montant_max: 200000,
    taux_max: 0.5,
    plafond_financement_public: 0.8,
    regles_cumul: {
      plafond_financement_public: 80,
      notes: 'Accessible uniquement dans les territoires ruraux couverts par un GAL LEADER. Vérifier éligibilité géographique auprès du GAL local.',
    },
    url_source: 'https://www.reseaurural.fr/leader',
    external_id: null,
    is_active: true,
  },
]

// ──────────────────────────────────────────────────────────────────────────────
// Export consolidé — 33 aides
// ──────────────────────────────────────────────────────────────────────────────

export const AIDES_ENRICHIES: AideInput[] = [
  ...AIDES_ETAT,
  ...AIDES_REGIONS,
  ...AIDES_DEPARTEMENTS,
  ...AIDES_FONDATIONS,
  ...AIDES_EUROPE,
]
